### PR TITLE
another attempt to fix fonts

### PR DESCRIPTION
**Pull request by lnussel**
follow up and revert of #342

### CODE REVIEW

**Comment by lnussel** [comment]
fwiw I couldn't test that yet. maybe need to craft a dud that overrides the file?

**Comment by wfeldt** [comment]
You don't need a dud for that. Just boot with `startshell=1` and remove the file before starting yast.

**Comment by wfeldt** [comment]
After playing with it a bit: I've no idea how to make yast prefer KacstOne over KacstBook for Farsi (other than removing KacstBook).

BTW:

- the yast layout is wrong, the progress window should be on the right side
- if you start yast with Farsi locale (`fa_IR`) the word 'Disk' in the progress window is not translated

**Comment by lnussel** [comment]
arabic-noto-naskh
persian-noto-naskh

**Comment by lnussel** [comment]
can we give this a try?

**Comment by wfeldt** [comment]
I'm already testing.

**Pull request merged**
