### PR TITLE
Support 32bit ARM (boo#1177264).

### PR DESCRIPTION
**Pull request by hramrach**
Signed-off-by: Michal Suchanek <msuchanek@suse.de>

### CODE REVIEW

**Comment by wfeldt** [comment]
This looks basically ok to me. But I couldn't test it.

So, does it build for armv6/7?

**Comment by hramrach** [comment]
It does build images but they do not include grub. Testing is indeed difficult for installtion-images.

**Comment by hramrach** [comment]
Found a typo in the filellists. Now the images build with all expected parts.

**Review by wfeldt — APPROVED** [review]
Then let's go for it.

**Pull request merged**
