### PR TITLE
openSUSE-MicroOS-release -> MicroOS-release

### PR DESCRIPTION
**Pull request by lnussel**

### CODE REVIEW

**Comment by wfeldt** [comment]
In SP2? For next QU?

There must be at least a bugnumber or somthing in the commit title to get this through the release process.

**Comment by lnussel** [comment]
actually I'm not sure anymore. And idea what branch that is: https://build.suse.de/package/show/SUSE:SLE-15-SP2:Update:Products:MicroOS/installation-images ?

**Comment by wfeldt** [comment]
That's from`master`; IIRC that's where Jiri did his experiments.

**Comment by lnussel** [comment]
i guess I have to maintain a local patch then

**Pull request closed without merging**
