### PR TITLE
Add support for riscv64

### PR DESCRIPTION
**Pull request by andreas-schwab**

### CODE REVIEW

**Comment by wfeldt** [comment]
Basically ok; do you have a bug/jira to add to the title? The branch is shared with sle15-sp3 and it will be blocked thete otherwise.

**Comment by andreas-schwab** [comment]
This is factory stuff only.

**Comment by wfeldt** [comment]
Fair enough, but I don't want to branch yet as sle15-sp3 & tw are too much in parallel atm.

**Review by wfeldt — APPROVED** [review]
lgtm

**Pull request merged**
