### PR TITLE
Replace Raleway fonts by WorkSans (jsc#SLE-14772)

### PR DESCRIPTION
**Pull request by jreidinger**
trello: https://trello.com/c/Ok8Jl7S4/2158-3-superwanted-theme-changes
jsc: https://jira.suse.com/browse/SLE-15714?focusedCommentId=1034010&page=com.atlassian.jira.plugin.system.issuetabpanels%3Acomment-tabpanel#comment-1034010

### CODE REVIEW

**Comment by jreidinger** [comment]
Do not merge it, we need to sync it to not break openQA multiple times.

**Comment by wfeldt** [comment]
please also adjust https://github.com/openSUSE/installation-images/blob/master/obs/installation-images.spec

**Review by wfeldt — APPROVED** [review]
Argh, I'm blind. :-(

**Comment by joseivanlopez** [comment]
Closed in favor of https://github.com/openSUSE/installation-images/pull/451.

**Pull request closed without merging**
