### PR TITLE
Fix grub branding for %{arm}

### PR DESCRIPTION
**Pull request by ggardet**

### CODE REVIEW

**Review by wfeldt — APPROVED** [review]
lgtm

**Comment by ggardet** [comment]
For Leap 15.3, should I submit it to `sle15-sp3` branch?

**Comment by wfeldt** [comment]
Thats's tricky ground. There's no separate Leap branch so indeed sle15-sp3 would be the way to go.

But sle15-sp3 development is more or less closed. There would have to be an official bug against sle15-sp3 to begin with. And it needs to be rated important enough.

**Comment by ggardet** [comment]
I created https://github.com/openSUSE/installation-images/pull/479 targeting sle15-sp3

**Pull request merged**
