### PR TITLE
More detailed listing of ifaces provided in ssh installation.

### PR DESCRIPTION
**Pull request by mchf**
bnc#956473

### CODE REVIEW

**Comment by mchf** [comment]
I was thinking of it whole weekend. In my POV 90% of users are satisfied with the message as is. 

However, there can still be some which would like to see alternatives. The function which is used tries to limit listing (doesn't show unconfigured ifaces, loopback), but to be honest I really don't know if that is useful. May be a question for PjM or UX?

**Comment by wfeldt** [comment]
We actually already show an ip list, gathered from wicked. It just happens to be invisible, as plymouth
erases the screen afterwards (but you see it with plymouth=0). :-(

Maybe we should just move the 'plymouth_off' line a bit up in the script (to before the /tmp/hostips line)?

**Comment by mchf** [comment]
thanks for tip, will try

**Comment by kobliha** [comment]
PLS see the respective Trello card, the list of ifaces - as it is shown now - is only confusing, containing a lot of unneeded information. Let's show only those items, that are necessary. And aligned and sorted.

**Comment by mchf** [comment]
@wfeldt Do you have some more comments regarding this PR? Pls see corresponding trello card for additional discussion. Thanks

**Comment by mchf** [comment]
Device listing was updated according UX comments here: https://github.com/yast/yast-installation/pull/364

**Pull request merged**
