### PR TITLE
Test 6

### PR DESCRIPTION
**Pull request by wfeldt**

### CODE REVIEW

**Comment by mvidner** [comment]
What is the difference between "Boot from Hard Disk" and "Boot Linux System"? Even when I can read the code implementing it I don't understand what the latter does.

**Comment by wfeldt** [comment]
... that's why it's in a submenu...

The 1st boots the hard disk, the 2nd boots an installed linux system.
Suggestions for a more descriptive label?

**Comment by mvidner** [comment]
how does 'Boot Linux System' know which partition to boot? /boot/x86_64/loader/linux is on the dvd, right?

**Comment by wfeldt** [comment]
It's extremely clever. :-)

**Comment by wfeldt** [comment]
maybe we should record the reviews after all...

**Comment by wfeldt** [comment]
to answer your question: linuxrc looks for an installed system

**Comment by mvidner** [comment]
Aaah. Maybe "Boot a Linux System via Linuxrc" would be more informative then? Anyway, LGTM now.

**Pull request merged**
