### PR TITLE
Add xen-tools-domU on x86 to get its udev rules (bsc#979002)

### PR DESCRIPTION
**Pull request by olafhering**
For  TW and SLE12.
Signed-off-by: Olaf Hering <olaf@aepfle.de>

### CODE REVIEW

**Comment by wfeldt** [comment]
If you are after udev rules wouldn't it be better added to the initrd?

**Comment by olafhering** [comment]
I have updated the reqest

**Comment by wfeldt** [comment]
Thanks; but you'll still want it in the rescue system, too.

**Comment by olafhering** [comment]
Why is it required for rescue? Does the initrd or rescue load the drivers and as such process the events?

**Comment by wfeldt** [comment]
initrd loads the drivers initially, but rescue is a complete system, running with init(1); so everything udevd has done, except for the module loading, is redone. In contrast, root is just an extension run in the same environment as the initrd.

So, if your udev rules just trigger some modules, you are ok putting them into the initrd alone. But if you also create some symlinks in /dev, you'll also need to adjust the rescue system.

**Comment by olafhering** [comment]
Ok, now I restored the rescue part.

**Pull request merged**
