### PR TITLE
Include common critera system role handler (jsc#SLE-12905)

### PR DESCRIPTION
**Pull request by lnussel**

### CODE REVIEW

**Comment by wfeldt** [comment]
Is that package included via package deps or do you BuildRequire it?

**Comment by lnussel** [comment]
I thought about adding a buildrequire to the spec file on sle

**Comment by wfeldt** [comment]
The spec is in this git repo; just wanted to mention this.

**Comment by lnussel** [comment]
I wonder why I keep forgetting this

**Comment by lnussel** [comment]
ouch, that was unintentional, wtf

**Pull request merged**
