### PR TITLE
Switch to vim-small (boo#1181633)

### PR DESCRIPTION
**Pull request by lnussel**
Also handle /usr/bin/vi pointing to alternatives

### CODE REVIEW

**Comment by lnussel** [comment]
Couldn't test this yet. The /usr/bin/vi fill will be needed for current vim submission to Factory

**Comment by wfeldt** [comment]
`vi` is a symlink to `vim`. Why would you change that?

**Comment by lnussel** [comment]
is about to become a symlink to /etc/alternatives/vi

**Comment by wfeldt** [comment]
Ok; do you have some bug number to add (to title)? This will also go to sle15-sp3.

**Comment by lnussel** [comment]
vi symlink is boo#1174564
if that goes to sle maybe we need to split off the vim-small part then. Should work there too though as vim-small is available in sle.

**Comment by wfeldt** [comment]
I've seen vim-small in SLE and the package looks no different than the TW one. I don't think anyone will notice the vim
difference.

**Review by wfeldt — APPROVED** [review]
lgtm

**Comment by wfeldt** [comment]
But you still need to change the title to contain a bug number.

**Comment by lnussel** [comment]
Ok, I've opened a separate bug for vim-small. The other one really is just about alternatives usage.

**Pull request merged**
