### PR TITLE
Add kernel modules necessary for Raspberry Pi 4 (bsc#1180336)

### PR DESCRIPTION
**Pull request by vianpl**
Reference: bsc#1180336
Signed-off-by: Nicolas Saenz Julienne <nsaenzjulienne@suse.de>

### CODE REVIEW

**Comment by vianpl** [comment]
One last thing left to fix would be adding the firmware files for RPi4 notably: `/lib/firmware/brcm/brcmfmac43455-sdio.raspberrypi,4-model-b.txt` is missing. That said, I'm not sure how this should be done. AFAIK there isn't any config file for firmware, yet the `.iso` contents' don't match `kernel-firmware.rpm's.`

**Comment by wfeldt** [comment]
Some notes:

  - don't modify `all_modules`; it's auto-generated from time to time to get an overview of existing modules - but it is not **used** for anything
  - there's no technical need to create a dedicated `aarch64` module section; these sections are left-overs from ancient times when we had module floppies and had to structure modules in some way; that said, I will not stop you doing this if you feel it's useful - I just want to point out that it is not strictly necessary
  - firmware files are auto-added based on the requirements extracted from the included modules
  - please add the bsc#XXX tag to the pull request title - it's needed for the auto-submission process

**Comment by vianpl** [comment]
> Some notes:
> 
> * don't modify `all_modules`; it's auto-generated from time to time to get an overview of existing modules - but it is not **used** for anything

Noted

> * there's no technical need to create a dedicated `aarch64` module section; these sections are left-overs from ancient times when we had module floppies and had to structure modules in some way; that said, I will not stop you doing this if you feel it's useful - I just want to point out that it is not strictly necessary

I'll remove it then, I was just following the patterns I saw.

> * firmware files are auto-added based on the requirements extracted from the included modules

OK, I now see how `brcmfmac's` modinfo lists a series of required firmware files, and it's incomplete.  Just for confirmation, wildcards in the firmware file names are honored, right?

> * please add the bsc#XXX tag to the pull request title - it's needed for the auto-submission process

Noted

Thanks!

**Comment by wfeldt** [comment]
> Just for confirmation, wildcards in the firmware file names are honored, right?

Good point; has it been implemented on the kernel side meanwhile? I'll have to adjust the scripts, then.

**Comment by vianpl** [comment]
> Good point; has it been implemented on the kernel side meanwhile? I'll have to adjust the scripts, then.

The good news is that we don't need a fix for SLE15-SP3, since we applied an out-of-tree patch specifically for this. But yes, Tumbleweed's kernel uses wildcards. See the following example, the file names are ultimately built mixing the patterns below and the board's name, which is extracted from firmware:

```
192:~ # modinfo brcmfmac
filename:       /lib/modules/5.11.0-rc7-next-20210215-00015-g198b95030295/kernel/drivers/net/wireless/broadcom/brcm80211/brcmfmac/brcmfmac.ko
license:        Dual BSD/GPL
description:    Broadcom 802.11 wireless LAN fullmac driver.
author:         Broadcom Corporation
firmware:       brcm/brcm/brcmfmac*-pcie.*.txt
firmware:       brcm/brcm/brcmfmac*-sdio.*.txt
firmware:       brcm/brcmfmac43012-sdio.bin
firmware:       brcm/brcmfmac4373-sdio.bin
[...]
```

**Comment by wfeldt** [comment]
Cool; I'll prepare an update.

**Review by wfeldt — APPROVED** [review]
lgtm

**Comment by vianpl** [comment]
It's something I'd like to backport into SLE15-SP3, should I take care of it or will it be done automatically?

**Comment by wfeldt** [comment]
this branch also goes to sle15-sp3

**Pull request merged**
